# Generated by Django 5.1.5 on 2025-01-29 11:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginside',
            name='id',
            field=models.UUIDField(default=uuid.UUID('2c9fd821-34c6-4e65-b762-358dd947b100'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='loginside',
            name='login_role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Manager', 'Manager')], max_length=10),
        ),
        migrations.AlterField(
            model_name='loginside',
            name='phone_number',
            field=models.CharField(default='Phone Number', max_length=15),
        ),
    ]
