# Generated by Django 5.1.5 on 2025-03-18 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginside',
            name='photo',
            field=models.ImageField(blank=True, default='img.png', null=True, upload_to='user_photo/'),
        ),
    ]
