# Generated by Django 5.1.5 on 2025-01-24 04:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginside',
            name='id',
            field=models.UUIDField(default=uuid.UUID('f92ae301-9b6c-46db-9a6c-b62928bc8d28'), editable=False, primary_key=True, serialize=False),
        ),
    ]
