# Generated by Django 5.1.4 on 2025-01-10 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginside',
            name='phone_number',
            field=models.IntegerField(null=True),
        ),
    ]
