# Generated by Django 5.1.5 on 2025-02-05 11:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginside',
            name='id',
            field=models.UUIDField(default=uuid.UUID('507dce6f-473c-437d-8707-f2db374dbf9e'), editable=False, primary_key=True, serialize=False),
        ),
    ]
