# Generated by Django 5.1.5 on 2025-01-30 11:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginside',
            name='id',
            field=models.UUIDField(default=uuid.UUID('74cba004-4663-49bf-a3cc-c6fa4a2f5731'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='loginside',
            name='login_role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Manager', 'Manager')], max_length=25),
        ),
    ]
