# Generated by Django 5.1.4 on 2025-01-20 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginside',
            name='first_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='loginside',
            name='phone_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='loginside',
            name='photo',
            field=models.ImageField(null=True, upload_to='user_photo/'),
        ),
    ]
