# Generated by Django 5.1.5 on 2025-01-21 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginside',
            name='email',
            field=models.EmailField(max_length=200),
        ),
    ]
