# Generated by Django 5.1.4 on 2025-01-10 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0002_alter_loginside_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginside',
            name='first_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
