# Generated by Django 5.1.4 on 2025-01-20 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0002_alter_loginside_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loginside',
            name='phone_number',
        ),
    ]
