# Generated by Django 5.1.5 on 2025-03-20 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0002_alter_loginside_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginside',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='user_photo/'),
        ),
    ]
