# Generated by Django 5.1.5 on 2025-02-06 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0002_alter_loginside_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login_Role',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False)),
            ],
        ),
    ]
