# Generated by Django 5.1.5 on 2025-01-27 10:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0002_alter_loginside_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginside',
            name='id',
            field=models.UUIDField(default=uuid.UUID('19f7d179-99f1-43cf-b95d-b2a9e019d22c'), editable=False, primary_key=True, serialize=False),
        ),
    ]
