# Generated by Django 5.1.5 on 2025-02-05 11:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0002_alter_loginside_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginside',
            name='id',
            field=models.UUIDField(default=uuid.UUID('123aa9f2-5c57-4ff5-952e-e756d2e7189e'), editable=False, primary_key=True, serialize=False),
        ),
    ]
