# Generated by Django 5.1.5 on 2025-01-29 11:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0003_alter_loginside_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginside',
            name='id',
            field=models.UUIDField(default=uuid.UUID('ca9f91fd-40bf-40b2-a178-3112739658e4'), editable=False, primary_key=True, serialize=False),
        ),
    ]
