# Generated by Django 5.1.5 on 2025-04-02 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0003_alter_loginside_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='login_role',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='role_images'),
        ),
    ]
