# Generated by Django 5.1.5 on 2025-01-27 13:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0003_alter_loginside_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginside',
            name='id',
            field=models.UUIDField(default=uuid.UUID('7a24a9dc-4127-493c-b4f7-5386761c54ad'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='loginside',
            name='phone_number',
            field=models.CharField(default='Phone Number', max_length=11),
        ),
    ]
