# Generated by Django 5.1.4 on 2025-01-20 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0003_remove_loginside_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginside',
            name='phone_number',
            field=models.CharField(default='number', max_length=90),
        ),
    ]
