# Generated by Django 5.1.5 on 2025-02-05 11:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0003_alter_loginside_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginside',
            name='id',
            field=models.UUIDField(default=uuid.UUID('e2d4a7cb-c5c8-4ebf-8ffb-692595cd97bc'), editable=False, primary_key=True, serialize=False),
        ),
    ]
