# Generated by Django 5.1.5 on 2025-03-03 08:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0003_alter_login_role_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginside',
            name='yi_role',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='loginside',
            name='id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
