# Generated by Django 5.1.4 on 2025-01-20 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0004_loginside_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginside',
            name='phone_number',
            field=models.CharField(blank=True, max_length=90, null=True),
        ),
    ]
