# Generated by Django 5.1.4 on 2025-01-10 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0004_alter_loginside_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loginside',
            name='photo',
        ),
    ]
