# Generated by Django 5.1.5 on 2025-01-27 13:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0004_alter_loginside_id_alter_loginside_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginside',
            name='id',
            field=models.UUIDField(default=uuid.UUID('30c279ac-714c-4c6b-887b-1008f0439be9'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='loginside',
            name='phone_number',
            field=models.CharField(default='Phone Number', max_length=15),
        ),
    ]
