# Generated by Django 5.1.5 on 2025-02-05 11:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0004_alter_loginside_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginside',
            name='id',
            field=models.UUIDField(default=uuid.UUID('5c36fd5a-f517-4d4e-805d-27e38952fac3'), editable=False, primary_key=True, serialize=False),
        ),
    ]
