# Generated by Django 5.1.5 on 2025-03-04 11:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0004_loginside_yi_role_alter_loginside_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginside',
            name='email',
            field=models.EmailField(max_length=200, unique=True, validators=[django.core.validators.EmailValidator()]),
        ),
        migrations.AlterField(
            model_name='loginside',
            name='phone_number',
            field=models.CharField(default='0', max_length=10, validators=[django.core.validators.RegexValidator(code='invalid_phone', message='Enter a valid phone number.', regex='^(\\+91[\\-\\s]?)?[0]?(91)?[789]\\d{9}$')]),
        ),
    ]
