# Generated by Django 5.1.5 on 2025-04-04 05:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_app", "0004_login_role_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loginside",
            name="photo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="user_photo/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpeg", "jpg", "png"]
                    )
                ],
            ),
        ),
    ]
