# Generated by Django 5.1.5 on 2025-01-29 11:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0004_alter_loginside_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginside',
            name='id',
            field=models.UUIDField(default=uuid.UUID('41500a36-1527-4144-aa97-b988ba1e4a28'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='loginside',
            name='login_role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Manager', 'Manager'), ('Masoom', 'Masoom'), ('Road Safety', 'Road Safety'), ('Health', 'Health'), ('Sports', 'Sports'), ('Accessibility', 'Accessibility'), ('Learning(YI Talks)', 'Learning(YI Talks)'), ('Climate action', 'Climate action'), ('Climate action', 'Climate action'), ('Innovation', 'Innovation'), ('Entrepreneurship', 'Entrepreneurship'), ('Branding & PR', 'Branding & PR'), ('Women Engagement (YIWE)', 'Women Engagement (YIWE)'), ('Culture Connect', 'Culture Connect'), ('Yi Angel', 'Yi Angel')], max_length=25),
        ),
    ]
