# Generated by Django 5.1.5 on 2025-01-29 12:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0005_alter_loginside_id_alter_loginside_login_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginside',
            name='id',
            field=models.UUIDField(default=uuid.UUID('2d7ebe6d-5b8e-49e5-b697-fc215c798c89'), editable=False, primary_key=True, serialize=False),
        ),
    ]
