# Generated by Django 5.1.5 on 2025-03-06 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0005_alter_loginside_email_alter_loginside_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginside',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='user_photo/'),
        ),
    ]
