# Generated by Django 5.1.4 on 2025-01-10 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0005_remove_loginside_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginside',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='user_photo/'),
        ),
    ]
