# Generated by Django 5.1.5 on 2025-01-28 04:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0005_alter_loginside_id_alter_loginside_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginside',
            name='id',
            field=models.UUIDField(default=uuid.UUID('341f5704-8733-49c0-becc-cef266ade662'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='loginside',
            name='login_role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Manager', 'Manager')], max_length=10),
        ),
    ]
