# Generated by Django 5.1.5 on 2025-01-28 04:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0006_alter_loginside_id_alter_loginside_login_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginside',
            name='id',
            field=models.UUIDField(default=uuid.UUID('548b318f-5def-46c0-97f1-36ef682ece47'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='loginside',
            name='login_role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Handler', 'Handler')], max_length=10),
        ),
    ]
