# Generated by Django 5.1.5 on 2025-01-29 12:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0006_alter_loginside_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginside',
            name='id',
            field=models.UUIDField(default=uuid.UUID('a9b3283c-c615-4245-ab3e-b2961edf9999'), editable=False, primary_key=True, serialize=False),
        ),
    ]
