# Generated by Django 5.1.5 on 2025-03-07 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0006_alter_loginside_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginside',
            name='login_role',
            field=models.ManyToManyField(to='admin_app.login_role', verbose_name='LoginRole'),
        ),
    ]
