# Generated by Django 5.1.5 on 2025-04-14 04:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_app", "0006_alter_login_role_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="login_role",
            name="name",
            field=models.CharField(
                choices=[
                    ("Admin", "Admin"),
                    ("Manager", "Manager"),
                    ("Masoom", "Masoom"),
                    ("Road Safety", "Road Safety"),
                    ("Yi Health", "Yi Health"),
                    ("Sports", "Sports"),
                    ("Accessibility", "Accessibility"),
                    ("Learning(YI Talks)", "Learning(YI Talks)"),
                    ("Climate action", "Climate action"),
                    ("Climate Change", "climate Change"),
                    ("Innovation", "Innovation"),
                    ("Entrepreneurship", "Entrepreneurship"),
                    ("Branding & PR", "Branding & PR"),
                    ("Women Engagement (YIWE)", "Women Engagement (YIWE)"),
                    ("Culture Connect", "Culture Connect"),
                    ("Yi Angel", "Yi Angel"),
                    ("Thalir", "Thalir"),
                    ("Yuva", "Yuva"),
                    ("Rural Initiatives", "Rural Initiatives"),
                    ("General Public", "General Public"),
                    ("Chapter", "Chapter"),
                    (
                        "Special Interest Group (S.I.G)",
                        "Special Interest Group (S.I.G)",
                    ),
                ],
                max_length=200,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="loginside",
            name="phone_number",
            field=models.CharField(
                default="0",
                max_length=10,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid phone",
                        message="Enter a valid phone number.",
                        regex="^(\\+91[\\-\\s]?)?[0]?(91)?[789]\\d{9}$",
                    )
                ],
            ),
        ),
    ]
