# Generated by Django 5.1.5 on 2025-03-07 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0007_alter_loginside_login_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginside',
            name='first_name',
            field=models.CharField(max_length=200, null=True, verbose_name='FirstName'),
        ),
    ]
