# Generated by Django 5.1.5 on 2025-01-28 11:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0007_alter_loginside_id_alter_loginside_login_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginside',
            name='id',
            field=models.UUIDField(default=uuid.UUID('5f6a07b6-174d-4351-b764-617e5127958b'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='loginside',
            name='login_role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Manager', 'Manager')], max_length=10),
        ),
    ]
