# Generated by Django 5.1.5 on 2025-01-29 13:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0007_alter_loginside_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginside',
            name='id',
            field=models.UUIDField(default=uuid.UUID('c726a955-382f-415c-9daf-5512abf149a1'), editable=False, primary_key=True, serialize=False),
        ),
    ]
