# Generated by Django 5.1.5 on 2025-04-17 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_app", "0008_alter_login_role_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Member_details",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("email", models.CharField(max_length=200)),
                ("phone", models.CharField(max_length=200)),
            ],
        ),
    ]
