# Generated by Django 5.1.4 on 2025-01-11 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0008_alter_loginside_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginside',
            name='photo',
            field=models.ImageField(null=True, upload_to='user_photo/'),
        ),
    ]
