# Generated by Django 5.1.5 on 2025-04-21 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_app", "0009_member_details"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="member_details",
            name="email",
        ),
        migrations.RemoveField(
            model_name="member_details",
            name="name",
        ),
        migrations.RemoveField(
            model_name="member_details",
            name="phone",
        ),
        migrations.AddField(
            model_name="member_details",
            name="Address",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="member_details",
            name="Company_Designation",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="member_details",
            name="Company_Name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="member_details",
            name="EC_Designation",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="member_details",
            name="EC_Member",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="member_details",
            name="Email_Address",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="member_details",
            name="First_Name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="member_details",
            name="Last_Name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="member_details",
            name="Phone_No",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="member_details",
            name="Profile_Photo",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="member_details",
            name="Vertical",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
