# Generated by Django 5.1.5 on 2025-04-21 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_app", "0010_remove_member_details_email_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="member_details",
            name="DOB",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="member_details",
            name="Membership_Type",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
