# Generated by Django 5.1.5 on 2025-04-21 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_app", "0011_member_details_dob_member_details_membership_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member_details",
            name="EC_Member",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
