# Generated by Django 5.1.5 on 2025-05-01 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_app", "0012_alter_member_details_ec_member"),
    ]

    operations = [
        migrations.AlterField(
            model_name="login_role",
            name="name",
            field=models.CharField(
                choices=[
                    ("Admin", "Admin"),
                    ("Manager", "Manager"),
                    ("Masoom", "Masoom"),
                    ("Road Safety", "RoadSafety"),
                    ("Yi Health", "Yi Health"),
                    ("Sports", "Sports"),
                    ("Accessibility", "Accessibility"),
                    ("Learning(YI Talks)", "Learning(YI Talks)"),
                    ("Membership", "Membership"),
                    ("Climate Change", "climate Change"),
                    ("Innovation", "Innovation"),
                    ("Entrepreneurship", "Entrepreneurship"),
                    ("Branding & PR", "Branding & PR"),
                    ("Women Engagement (YIWE)", "Women Engagement (YIWE)"),
                    ("Culture Connect", "Culture Connect"),
                    ("Yi Angel", "Yi Angel"),
                    ("Thalir", "Thalir"),
                    ("Yuva", "Yuva"),
                    ("Rural Initiatives", "Rural Initiatives"),
                    ("General Public", "General Public"),
                    (
                        "Special Interest Group (S.I.G)",
                        "Special Interest Group (S.I.G)",
                    ),
                    ("Chapter", "Chapter"),
                ],
                max_length=200,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
