# Generated by Django 5.1.5 on 2025-05-02 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_app", "0014_alter_login_role_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="member_details",
            name="IG_Link",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="member_details",
            name="Linkedin_Link",
            field=models.URLField(blank=True, null=True),
        ),
    ]
