# Generated by Django 5.1.5 on 2025-05-02 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_app", "0015_member_details_ig_link_member_details_linkedin_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member_details",
            name="DOB",
            field=models.DateField(blank=True, max_length=200, null=True),
        ),
    ]
