# Generated by Django 5.1.5 on 2025-05-02 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_app", "0016_alter_member_details_dob"),
    ]

    operations = [
        migrations.AddField(
            model_name="loginside",
            name="Company_Designation",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="loginside",
            name="Company_Name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="loginside",
            name="DOB",
            field=models.DateField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="loginside",
            name="IG_Link",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="loginside",
            name="Linkedin_Link",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="member_details",
            name="Address",
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
