# Generated by Django 5.1.5 on 2025-05-05 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "admin_app",
            "0017_loginside_company_designation_loginside_company_name_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="loginside",
            name="DOB",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
