# Generated by Django 5.1.5 on 2025-05-05 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_app", "0019_alter_loginside_dob"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loginside",
            name="DOB",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
