# Generated by Django 5.1.5 on 2025-05-05 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_app", "0020_alter_loginside_dob"),
    ]

    operations = [
        migrations.AddField(
            model_name="loginside",
            name="Company_Address",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
