# Generated by Django 5.1.5 on 2025-05-05 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_app", "0022_alter_member_details_dob"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member_details",
            name="DOB",
            field=models.DateField(blank=True, max_length=200, null=True),
        ),
    ]
