# Generated by Django 5.1.5 on 2025-05-05 07:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_app", "0023_alter_member_details_dob"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member_details",
            name="Email_Address",
            field=models.EmailField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="member_details",
            name="Phone_No",
            field=models.CharField(
                default="0",
                max_length=10,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid phone",
                        message="Enter a valid phone number.",
                        regex="^(\\+91[\\-\\s]?)?[0]?(91)?[789]\\d{9}$",
                    )
                ],
            ),
        ),
    ]
