# Generated by Django 5.1.5 on 2025-02-14 05:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('your_name', models.CharField(max_length=50)),
                ('event_name', models.CharField(blank=True, max_length=200)),
                ('event_venue', models.CharField(blank=True, max_length=200)),
                ('event_expense', models.IntegerField(blank=True, default=0)),
                ('date', models.CharField(max_length=200)),
                ('role_yi', models.CharField(max_length=200)),
                ('project_vertical', models.CharField(max_length=200)),
                ('project_stakeholder', models.CharField(max_length=200)),
                ('yi_pillar', models.CharField(max_length=200)),
                ('social_link', models.URLField(max_length=300)),
                ('which_SIG', models.CharField(blank=True, max_length=200, null=True)),
                ('event_handle', models.CharField(max_length=200)),
                ('total_impact', models.IntegerField(blank=True, default=1)),
                ('school', models.CharField(blank=True, max_length=200, null=True)),
                ('collage', models.CharField(blank=True, max_length=200, null=True)),
                ('associate_partner', models.CharField(blank=True, max_length=200, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Event_Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_photo', models.ImageField(null=True, upload_to='event_photo/')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager_app.event_data')),
            ],
        ),
    ]
