# Generated by Django 5.1.5 on 2025-01-20 09:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('your_name', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('role_yi', models.CharField(default='role_yi', max_length=200)),
                ('project_vertical', models.CharField(max_length=200)),
                ('project_stakeholder', models.CharField(max_length=200)),
                ('yi_pillar', models.CharField(max_length=200)),
                ('social_link', models.URLField(max_length=300)),
                ('which_SIG', models.CharField(default='SIG', max_length=200)),
                ('event_handle', models.CharField(max_length=200)),
                ('total_impact', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
