# Generated by Django 5.1.5 on 2025-01-30 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event_data',
            name='associate_partner',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
