# Generated by Django 5.1.5 on 2025-01-23 13:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='event_data',
            name='role_yi',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='event_data',
            name='user',
            field=models.ForeignKey(default='1', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='event_data',
            name='which_SIG',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
