# Generated by Django 5.1.5 on 2025-02-07 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event_data',
            name='which_SIG',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
