# Generated by Django 5.1.5 on 2025-01-29 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event_data',
            name='event_expense',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AddField(
            model_name='event_data',
            name='event_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='event_data',
            name='event_photo',
            field=models.ImageField(null=True, upload_to='event_photo'),
        ),
        migrations.AddField(
            model_name='event_data',
            name='event_venue',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='event_data',
            name='place_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='event_data',
            name='date',
            field=models.CharField(max_length=200),
        ),
    ]
