# Generated by Django 5.1.5 on 2025-02-19 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager_app', '0002_alter_event_image_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event_data',
            name='event_handle',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
