# Generated by Django 5.1.5 on 2025-02-03 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager_app', '0002_alter_event_data_associate_partner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event_data',
            old_name='place_name',
            new_name='collage',
        ),
        migrations.AddField(
            model_name='event_data',
            name='school',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
