# Generated by Django 5.1.5 on 2025-01-29 12:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager_app', '0002_event_data_event_expense_event_data_event_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='event_data',
            name='total_impact',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='event_data',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
