# Generated by Django 5.1.5 on 2025-01-29 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager_app', '0003_alter_event_data_total_impact_alter_event_data_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event_data',
            name='event_photo',
            field=models.ImageField(null=True, upload_to='event_photo/'),
        ),
        migrations.AlterField(
            model_name='event_data',
            name='total_impact',
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
