# Generated by Django 5.1.5 on 2025-02-07 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager_app', '0003_alter_event_data_associate_partner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event_data',
            name='which_SIG',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
