# Generated by Django 5.1.5 on 2025-01-21 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager_app', '0003_alter_event_data_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event_data',
            name='user',
        ),
    ]
