# Generated by Django 5.1.5 on 2025-03-19 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager_app', '0003_alter_event_image_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event_data',
            name='event_expense',
            field=models.BigIntegerField(default=0),
        ),
    ]
