# Generated by Django 5.1.5 on 2025-02-24 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager_app', '0003_alter_event_data_event_handle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event_image',
            name='event_photo',
            field=models.ImageField(null=True, upload_to='event_photo'),
        ),
    ]
