# Generated by Django 5.1.5 on 2025-02-03 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager_app', '0003_rename_place_name_event_data_collage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event_data',
            name='associate_partner',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='event_data',
            name='which_SIG',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
