# Generated by Django 5.1.5 on 2025-02-07 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager_app', '0004_alter_event_data_which_sig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event_data',
            name='event_expense',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
