# Generated by Django 5.1.5 on 2025-01-29 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager_app', '0004_alter_event_data_event_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event_data',
            name='associate_partner',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
