# Generated by Django 5.1.5 on 2025-02-24 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager_app', '0004_alter_event_image_event_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event_image',
            name='event_photo',
            field=models.ImageField(blank=True, null=True, upload_to='event_photo'),
        ),
    ]
