# Generated by Django 5.1.5 on 2025-03-19 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager_app', '0004_alter_event_data_event_expense'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event_data',
            name='event_expense',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
