# Generated by Django 5.1.5 on 2025-02-25 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager_app', '0005_alter_event_image_event_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event_data',
            name='event_expense',
            field=models.BigIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='event_data',
            name='total_impact',
            field=models.BigIntegerField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='event_image',
            name='event_photo',
            field=models.ImageField(blank=True, null=True, upload_to='event_photo/'),
        ),
    ]
