# Generated by Django 5.1.5 on 2025-03-24 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager_app', '0005_alter_event_data_event_expense'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event_data',
            name='event_expense',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
    ]
