# Generated by Django 5.1.5 on 2025-03-03 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager_app', '0006_alter_event_data_event_expense_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event_data',
            name='date',
            field=models.DateField(),
        ),
    ]
