# Generated by Django 5.1.5 on 2025-03-24 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager_app', '0006_alter_event_data_event_expense'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event_data',
            name='event_venue',
            field=models.TextField(blank=True),
        ),
    ]
