# Generated by Django 5.1.5 on 2025-03-25 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager_app', '0007_alter_event_data_event_venue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event_data',
            name='event_handle',
        ),
        migrations.AddField(
            model_name='event_data',
            name='event_member',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='event_data',
            name='select_ec_member',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
