# Generated by Django 5.1.5 on 2025-01-21 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager_app', '0007_alter_event_data_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event_data',
            name='role_yi',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='event_data',
            name='which_SIG',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
