# Generated by Django 5.1.5 on 2025-03-03 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager_app', '0007_alter_event_data_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event_data',
            name='date',
            field=models.CharField(max_length=200),
        ),
    ]
