# Generated by Django 5.1.5 on 2025-02-11 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager_app', '0007_alter_event_data_associate_partner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event_data',
            name='associate_partner',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
