# Generated by Django 5.1.5 on 2025-04-03 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manager_app", "0008_remove_event_data_event_handle_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="event_data",
            name="event_description",
            field=models.TextField(blank=True, max_length=700, null=True),
        ),
    ]
