# Generated by Django 5.1.5 on 2025-02-05 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager_app', '0008_alter_event_data_associate_partner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event_data',
            name='associate_partner',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
