# Generated by Django 5.1.5 on 2025-01-22 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager_app', '0008_alter_event_data_role_yi_alter_event_data_which_sig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event_data',
            name='which_SIG',
            field=models.CharField(default='SIG', max_length=200, null=True),
        ),
    ]
