# Generated by Django 5.1.5 on 2025-02-11 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager_app', '0009_alter_event_data_associate_partner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event_data',
            name='event_photo',
        ),
        migrations.CreateModel(
            name='Event_Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_photo', models.ImageField(null=True, upload_to='event_photo/')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_image', to='manager_app.event_data')),
            ],
        ),
    ]
