# Generated by Django 5.1.5 on 2025-04-07 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manager_app", "0009_event_data_event_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event_data",
            name="event_expense",
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
