# Generated by Django 5.1.5 on 2025-02-11 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager_app', '0010_remove_event_data_event_photo_event_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event_image',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_photo', to='manager_app.event_data'),
        ),
    ]
