# Generated by Django 5.1.5 on 2025-02-13 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0004_remove_loginside_login_role_loginside_login_role'),
        ('manager_app', '0011_alter_event_image_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event_data',
            name='project_vertical',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_app.login_role'),
        ),
    ]
