# Generated by Django 5.1.5 on 2025-02-13 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager_app', '0012_alter_event_data_project_vertical'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event_data',
            name='project_vertical',
            field=models.CharField(max_length=200),
        ),
    ]
